### ISSUE TITLE
Unexpected headline colors in sent newsletter

### ISSUE THREAD

**Issue by iamstevebeatty** [Automattic/newspack-newsletters#122]
As a newletter recipients, I was surprised to find the headlines from the Post Inserter come across in blue. Presumably it does that because that's the specified color for links, and it would happen with newly placed stories in other parts of the newsletter, too.

**Comment by iamstevebeatty** [comment]
![image](https://user-images.githubusercontent.com/48489469/80045893-6de3da80-84ce-11ea-8d06-685c2c796b45.png)

**Comment by thomasguillot** [comment]
Closed with #125 now links will inherit the colour (black by default) with an underline.
