### ISSUE TITLE
Pre-Send Confirmation

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-newsletters#139]
The custom implementation of the Publish/Send button has done away with pre-publish checklist, which makes it very easy to send a campaign, possibly without intending to. We should add some sort of confirmation UI, whether it's an "are you sure?" modal or a "ready to send" checkbox. We also could potentially do this only if the user has not sent themselves a test. 

> "will I ever not have a frisson of panic every time I hit the send button on the NL?" -- @kristastevens

**Comment by adekbadek** [comment]
I think something akin to pre-publish sidebar/modal would be the best, as the user is likely to already be familiar with it. WDYT @thomasguillot ?

**Comment by thomasguillot** [comment]
It actually happened to me!

I agree, we need something. Ideally we reproduce the pre-publish in the sidebar so we keep a similar pattern with Posts/Pages/Other CPTs. __IF__ we really can't do it this way, then I suppose a modal would be the second best choice since the user knows the pattern from the "Send Test".

**Comment by adekbadek** [comment]
I looked at how Mailchimp does it, and since mimicking pre-publish checks would be quite hacky, I propose a similar modal:

![image](https://user-images.githubusercontent.com/7383192/80796917-bec79300-8ba0-11ea-81fd-3a46a6dc2fc0.png)

**Comment by thomasguillot** [comment]
Based on the "Change Layout" modal for style + wording, we could do something like this:

![confirmation](https://user-images.githubusercontent.com/177929/80801038-1109b380-8ba3-11ea-9f44-cac121c824df.png)
