### ISSUE TITLE
Posts Inserter Goes Haywire When Featured Image Absent

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-newsletters#146]
If one of the posts being inserted by Posts Inserter lacks a featured image the Image block appears to go into an infinite loop where the Upload button blinks constantly between disabled and enabled state, and the other two buttons blink on and off.

Video demo: https://cloudup.com/c1dknYSpy2p

### Steps To Reproduce

1) Remove Featured Image from top Post.
2) Create a Newsletter, Insert Daily/Weekly template.
3) Observe blinking buttons in both Post Inserter instances.

First reported by @iamstevebeatty

**Comment by adekbadek** [comment]
For me, the UI flicker/infinite loop issue is there regardless of whether posts have featured images.
