### ISSUE TITLE
Support multiple providers

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/newspack-newsletters#150]
![1 step1](https://user-images.githubusercontent.com/177929/80365478-93caff80-887f-11ea-9bb9-70879f110e7e.png)
![2 step2](https://user-images.githubusercontent.com/177929/80365480-94639600-887f-11ea-818f-cee3832b44b7.png)

_Note: we should have same behaviour for Newsletters > Settings_

**Comment by bph** [comment]
Any chance that one of the providers could a Sendy.co instance? 
[Their API ](https://sendy.co/api) has a 'create campaign' method.
