### ISSUE TITLE
Post Inserter block draws from entire site, may bring in unintended posts

### ISSUE THREAD

**Issue by iamstevebeatty** [Automattic/newspack-newsletters#155]
The smallest post to any page will show up as the most recent post in the newsletter. For instance, that could be a cop brief, an obituary or review of community theater. 

That could be fine, unless there's a lot of them, and the person editing the newsletter has to delete a bunch of things. 

Is there a way to draw just the posts that appear on the homepage at the moment?

**Comment by adekbadek** [comment]
1. Wouldn't category filtering solve the issue? I assume the "real" posts might have specific categories.
1. We can add category exclusion, so posts like obituaries and reviews might be filtered out.

**Comment by jeffersonrabb** [comment]
Closing - covered by https://github.com/Automattic/newspack-newsletters/issues/155
