### ISSUE TITLE
Convert Newsletter To Post

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-newsletters#171]
A Newspack customer recently asked whether it was possible to convert a Newsletter to a normal Post, so that Newsletter content could be fully integrated into the site. This could be useful for a site section such as a Newsletter Archive. This seems like it should be relatively easy since the Newsletter is already a post, but how would we approach the UI for this?

cc: @thomasguillot

**Comment by thomasguillot** [comment]
![Screenshot 2020-04-30 at 12 47 03](https://user-images.githubusercontent.com/177929/80706758-c0ca1d00-8ae0-11ea-96d0-8aa9f3f2616c.png)

What do you think of adding the functionality where we list all the newsletters?

Clicking the button would take the user to the Post Editor and copy all the blocks from the Newsletter. They can then add tags, categories, etc...

**Comment by sonjaleix** [comment]
Hi Newspack team, I'd like to weigh in on this for the Newspack client who requested this feature.

> Clicking the button would take the user to the Post Editor and copy all the blocks from the Newsletter. They can then add tags, categories, etc...
@thomasguillot do you mean that there is a way to click one button and the content of the newsletter would be automatically copied into a new post? Or would the copy/pasting happen manually?

**Comment by thomasguillot** [comment]
> @thomasguillot do you mean that there is a way to click one button and the content of the newsletter would be automatically copied into a new post?

@sonjaleix yes, that's the idea 😊

![Kapture 2020-05-06 at 17 26 33](https://user-images.githubusercontent.com/177929/81202869-190c8d80-8fbf-11ea-82d2-bf771dcd4002.gif)

**Comment by Retrofitterdk** [comment]
Copying a newsletter to a regular post seems a cumbersome way to create a newsletter archive, while also duplicating the content, so it exists twice in the database.

Is there any reason, why you couldn’t just add filters to the register_post_type function, so developers could set ’public’ and ’has_archive’ to true.

This would also make it easier to style newsletter (on the site) differently than regular posts.

**Comment by sonjaleix** [comment]
I agree with @Retrofitterdk in regards to the duplicate content and it being easier to style the newsletter different on the site from regular posts. 

Ideally there would be a UI option to set the newsletters to 'private' or 'private' for this feature.

**Comment by jeffersonrabb** [comment]
Related: https://github.com/Automattic/newspack-newsletters/issues/214

**Comment by sonjaleix** [comment]
Checking in to see if there might be any progress on this feature soon?

**Comment by dkoo** [comment]
@sonjaleix I've been working on this here: https://github.com/Automattic/newspack-newsletters/pull/272

**Comment by dkoo** [comment]
@sonjaleix This has been merged as of today and should be going out as part of this week's release.

**Comment by dkoo** [comment]
@sonjaleix This is now being deployed to production sites. Just to note, you may need to flush permalinks for the new public posts to be visible (go to Settings > Permalinks and click "Save" without making any changes).
