### ISSUE TITLE
Template Thumbnails Lack Backgrounds With Gutenberg Plugin Off

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-newsletters#172]
- Switch off Gutenberg plugin
- Create a Newsletter.
- Observe lack of backgrounds on template thumbnails.

This also seems to be the case with Gutenberg plugin v. 8.0.

<img width="1398" alt="Screen Shot 2020-04-29 at 8 06 14 PM" src="https://user-images.githubusercontent.com/1477002/80659268-79974a00-8a56-11ea-92ba-7f066f02274a.png">

**Comment by thomasguillot** [comment]
Yeah in G 8.0.0 they changed the way the patterns are being displayed so they removed the styles that I was using 😭
