### ISSUE TITLE
With Gutenberg disabled, layouts preview missing padding

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/newspack-newsletters#177]
With WP 4.5.1 and Gutenberg disabled we are missing some padding in for the preview thumbnail.

Padding is currently added via:
https://github.com/Automattic/newspack-newsletters/blob/master/src/components/template-modal/style.scss#L217
https://github.com/Automattic/newspack-newsletters/blob/master/src/editor/layout/style.scss#L22

The `.is-root-container` class is currently only available when Gutenberg is active.

See #175

**Comment by miguelpeixe** [comment]
@thomasguillot is this still an issue? I'm wondering how would the newsletter work without Gutenberg.

**Comment by thomasguillot** [comment]
I meant Gutenberg, the plugin, but this issue is probably not true anymore anyway 😊
