### ISSUE TITLE
Limit the blocks you can add to a column

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/newspack-newsletters#184]
We should probably not allow all the available blocks to be added to a Column, especially the Post Inserter:

![Screenshot 2020-05-01 at 15 54 13](https://user-images.githubusercontent.com/177929/80814589-0f041c80-8bc4-11ea-99b3-f53e7486ed92.png)

We already have a notice for Group and Columns but ideally we should simply remove them.

**Comment by adekbadek** [comment]
> especially the Post Inserter:

What other blocks should be restricted? 

With the way Column block is set up, it's not possible to restrict the [allowed blocks](https://developer.wordpress.org/block-editor/tutorials/block-tutorial/nested-blocks-inner-blocks/#allowed-blocks), but a notice can be displayed.

**Comment by adekbadek** [comment]
This issue needs more details – closing for now, feel free to reopen.
