### ISSUE TITLE
Overlaid blocks in the editor

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-newsletters#190]
Given a sequence of blocks: paragraph, columns, the blocks in the editor will be overlaid:

![image](https://user-images.githubusercontent.com/7383192/80962851-1c144c00-8e0e-11ea-9aa9-6a7c2deac110.png)

Introduced in #182 with these lines:

https://github.com/Automattic/newspack-newsletters/blob/f35482f61e579bd5a026a247070a23bd5bf8755e/src/editor/style.scss#L57-L58

**Comment by thomasguillot** [comment]
#195 should fix this
