### ISSUE TITLE
Add a fonts setting

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/newspack-newsletters#198]
We could add a panel in the sidebar to allow users to pick the fonts they want -- carefully selected web-safe fonts -- for headings and the body.

At the moment we only support a non-web-safe font: Ubuntu (MJML default).

![1 init](https://user-images.githubusercontent.com/177929/81283642-e1502500-9054-11ea-910e-ae1269ca6fcb.png)
![2 select](https://user-images.githubusercontent.com/177929/81283646-e2815200-9054-11ea-8c96-c64c06ff305f.png)
![3 change-body](https://user-images.githubusercontent.com/177929/81283648-e3b27f00-9054-11ea-8a4a-34b74d1970da.png)
![4 change-heading](https://user-images.githubusercontent.com/177929/81283652-e44b1580-9054-11ea-9103-2ad5f3390244.png)

**Comment by kinseywilson** [comment]
A couple of quick observations about visual display of the newsletter. The header should be constrained to the width of the newsletter itself, and not span to the with of the browser display:

![image](https://user-images.githubusercontent.com/37083693/83355619-9614f380-a32e-11ea-9450-70ab529c04f0.png)

**Comment by kinseywilson** [comment]
This is the standard used by most news websites, large and small:

![image](https://user-images.githubusercontent.com/37083693/83355651-cbb9dc80-a32e-11ea-91c8-0a569d71db6a.png)

![image](https://user-images.githubusercontent.com/37083693/83355664-e55b2400-a32e-11ea-8530-d698217bf385.png)

**Comment by jeffersonrabb** [comment]
@kinseywilson, notes on the header display probably make more sense in a separate issue, or possibly in https://github.com/Automattic/newspack-newsletters/issues/211 (which would then need to be reopened).

**Comment by kinseywilson** [comment]
> 

The shaded section directly below this opening part was creating using the Post Inserter, devised by our own Jefferson Rabb. We asked it to pull the four most recent items published on newspack.blog, and it dropped in images, headlines and text with a couple of clicks.
--

This is from the first version of the newsletter Steve sent out using the plugin. The body copy of the items pulled from the inserter needs to be styled in a way that is much more consistent with the rest of the news letter. Here's what Post Inserter copy looks like (I shrunk it down considerably to capture the full contents):

![image](https://user-images.githubusercontent.com/37083693/83355819-ca3ce400-a32f-11ea-9ddd-438a18270880.png)

Versus other elements:
![image](https://user-images.githubusercontent.com/37083693/83355841-e80a4900-a32f-11ea-8c6f-60593947f7d4.png)
