### ISSUE TITLE
Possible fix for initial newsletter plugin setup error

### ISSUE THREAD

**Issue by iamstevebeatty** [Automattic/newspack-newsletters#205]
I don’t get any errors if I change my workflow a bit. After installing and activating the plugin, i go straight to Newsletter --> Settings and enter my info. Things work as expected after that. That settings page is barebones, not like the helpful one Jeff set up with links to get keys and such. Seems like if we require the settings to be entered before you can hit “add new,” that’d do the trick. And maybe change the menu to Setup, so it has that one-time feel to it. This was successful on the newspack.blog and on the model home.

**Comment by jeffersonrabb** [comment]
Moving this to be a comment on the original issue, https://github.com/Automattic/newspack-newsletters/issues/203.
