### ISSUE TITLE
Would like to have full-width banner for newsletters, as in Mailchimp

### ISSUE THREAD

**Issue by iamstevebeatty** [Automattic/newspack-newsletters#211]
Full-width images aren't supported in our plugin:
![Screen Shot 2020-05-20 at 12 44 34 PM](https://user-images.githubusercontent.com/48489469/82482660-cc37b500-9a9c-11ea-88aa-5820912306e1.png)

This is what Mailchimp serves up:
![image (5)](https://user-images.githubusercontent.com/48489469/82482736-e6719300-9a9c-11ea-944d-c5dc948e9482.png)

Even when I drop in a very large image (1924 x 215), it downsizes it and limits me to Wide Width. And it still doesn't produce what it shows in the editor:
Editor view: 
![Screen Shot 2020-05-20 at 1 25 57 PM](https://user-images.githubusercontent.com/48489469/82483323-d27a6100-9a9d-11ea-81c7-f9c9576a2297.png)
Result in my inbox: 
![Screen Shot 2020-05-20 at 1 26 52 PM](https://user-images.githubusercontent.com/48489469/82483356-e32ad700-9a9d-11ea-9b2c-fa597606f1d0.png)

**Comment by iamstevebeatty** [comment]
As a note, the background color in the area that's filled by the Post Inserters in the default layouts fills full width and keeps up with changes in the window size. 
![image](https://user-images.githubusercontent.com/48489469/82494723-a10a9100-9aaf-11ea-80fb-e9f342c6d52f.png)

**Comment by adekbadek** [comment]
@iamstevebeatty Would a full-width group, with the image inside and a background color, solve the issue? 
The Posts Inserters in the default layouts are wrapped in colored groups.

**Comment by iamstevebeatty** [comment]
I did just that now on the newsletter. I didn't immediately have the
ability to put our logo on a transparent background, but Laurel helped out
on that. Still, I wonder if other publications expect to simply paste their
logo and have it work, rather than these couple of steps that work around
it.

**Comment by adekbadek** [comment]
This in unfortunately not possible (in a way that would be reliable across email clients) :/ I've tried to do it in a pretty hacky way, as suggested in https://github.com/mjmlio/mjml/issues/1782, but setting a fixed height on an image makes it not responsive.
