### ISSUE TITLE
Support For Mailchimp Segments

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-newsletters#22]
Add support for Mailchimp segments: https://us7.admin.mailchimp.com/lists/members?id=453669&previewName=Contacts#p:1-s:10-sa:last_update_time-so:false

**Comment by tmmbecker** [comment]
Quite a few publishers have asked about this recently - MS Today and The Real News to name two.

**Comment by kendraschaefer** [comment]
Any progress on this? We're using this plugin, and groups are not very flexible in the context of our system, would really help to be able to use segments - wanted to see if this is still on the table?
