### ISSUE TITLE
Button Colors Lost In Emails

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-newsletters#229]
Button color settings are overridden when emails are sent. The background and text colors are visible in the editor, but in the email the buttons are always white on black. 

To reproduce:

- Create a Newsletter
- Click on a button, open Color Settings panel, choose text and background colors. 
- Send a test email.
- Observe the button in the email is white text on a black background.

**Comment by janus-reith** [comment]
The text color can be set, which worked when I tested and also makes sense codewise as the attribute `color` is parsed there.
The background color however will  be ignored, as the `get_colors` function which the button uses only checks for a `background-color` property, while button uses `background`:

https://github.com/Automattic/newspack-newsletters/blob/master/includes/class-newspack-newsletters-renderer.php#L101L105
