### ISSUE TITLE
Support vertical center alignment on (mj-)column

### ISSUE THREAD

**Issue by janus-reith** [Automattic/newspack-newsletters#231]
Currently, a warning is shown if the `verticalAlignment`attribute for blocks of type "core/column" is set to `center`.

mj-column does support center alignment, but calls it "middle".

In the renderer just check if `verticalAlignment` equals "center" and subsitute that with "middle" : https://github.com/Automattic/newspack-newsletters/blob/ccaebbc300f183685239817c00022e16eedd9635/includes/class-newspack-newsletters-renderer.php#L439

Tested it, works fine.

**Comment by adekbadek** [comment]
Hi @janus-reith, thanks for the tip! 
I've found that in multi-column layout, the tallest column has to be `vertical-align="middle"` in order to make smaller columns handle the middle alignment, does that check out with your testing?

**Comment by janus-reith** [comment]
@adekbadek Yes I can confirm, although this seems to be the general way `vertical-align="middle"` is interpreted in HTML.
Made a quick example here: https://codesandbox.io/s/clever-star-2zgog?file=/index.html
This is not an issue for gutenberg columns, as these use flexbox and `align-self` for each column.

So this could indeed lead to problems.
Simply enabling it could lead to unexpected results, on the other hand always showing a warning like _align: middle only works if the tallest column has align-middle_ could really disrupt the user experience, and currently also alter the element position.

Still, to really get some more sophisticated layouts done I consider the ability to center-align elements vital. 

I wonder if actually measuring column heights is something that could be considered, to only show a warning if really necessary? - Preferably without needing to change anything in the core column component, or outside newspack-newsletters in general.

Looking at this:
https://github.com/Automattic/newspack-newsletters/blob/43fb115d3c7bd6cdf930a0843a18f6d7dd5ad690/src/editor/blocks-validation/blocks-filters.js#L52

It looks like the warnings work by wrapping each individual block, with access to their respective attributes.
Now if somehow the wrapping columns block and each column in there could share context, it should be simple to get this done, but I did not check further how `addFilter` works here and which restrictions this might impose, or if there maybe is a gutenberg-included solution for this already.

**Comment by adekbadek** [comment]
This is essentially an issue of translating a flexbox layout to a non-flexbox one, which gets pretty complicated. 
On one hand there's that, on another we could support an "all columns middle-aligned" layout more easily – I've submitted a PR: #235

**Comment by janus-reith** [comment]
Great, seems to be the most simple solution!

**Comment by adekbadek** [comment]
Thanks again for digging into that, @janus-reith !
