### ISSUE TITLE
Add Category Exclusion, Tags, Tag Exclusion To Posts Inserter

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-newsletters#234]
Posts Inserter block should have the same filtering capabilities as Homepage Posts, to make it easier to mirror homepage content.

**Comment by jeffersonrabb** [comment]
Got another request for this one from CalMatters. 

> Is there a way to exclude a category? We would love to have almost all of our categories but exclude a couple (vs. including all 20+ of the ones we do want.)

**Comment by dkoo** [comment]
It shall be so in the next release!
