### ISSUE TITLE
Mailchimp tags: handle tag creation

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-newsletters#242]
#241 Adds segmentation via tag selection. If a tag is not found, it's discarded – it should be [created](https://mailchimp.com/developer/guides/how-to-use-tags/) instead.

**Comment by miguelpeixe** [comment]
#556 changes the UI and improves support for groups/tags/segments selection for segmentation. I don't think creating new audience tags/segments is something that we should support as a feature. It's a complex feature that Mailchimp already covers with a comprehensive UI.

I believe we can readdress this issue if we design a specific segmentation strategy related to the Newspack ecosystem.
