### ISSUE TITLE
Sync with MC before sending test, previewing on MC

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-newsletters#25]
Currently, before previewing the email on MC, user has to save the draft after making changes. This is not intuitive, and we can save the post behind the scenes when those actions are performed.
The MC campaign update response should be awaited before redirecting to preview or sending test email request.

**Comment by jeffersonrabb** [comment]
Related: https://github.com/Automattic/newspack-newsletters/issues/33
