### ISSUE TITLE
Can't center social icons or buttons in newsletter

### ISSUE THREAD

**Issue by iamstevebeatty** [Automattic/newspack-newsletters#258]
The social icons can't be centered, either working with one icon or the parent Social Icons block. (This may be another matter that's just beyond me, but once an icon is eliminated, say, LinkedIn, and then they realize they have an account there, how can I add a single icon to the existing group? )

![Screen Shot 2020-07-07 at 11 14 07 AM](https://user-images.githubusercontent.com/48489469/86811188-3ef7f200-c043-11ea-974c-7f44cb1450f8.png)

Also, the Button block nor Buttons parent block don't offer a choice for alignment. This probably isn't as urgent because they default to centered, which is a good place for them. Just seems odd I don't have that alignment choice. 

![Screen Shot 2020-07-07 at 11 14 19 AM](https://user-images.githubusercontent.com/48489469/86811318-6353ce80-c043-11ea-9bb5-c11c47d30773.png)

To reproduce
Start a newsletter.
Add Social Icons block 
Note the lack of alignment options on the menu
Same with button(s)

**Comment by jeffersonrabb** [comment]
Social icon alignment resolved in https://github.com/Automattic/newspack-newsletters/pull/257
