### ISSUE TITLE
Layouts: Tweak Support layout to not use top-level Group block

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-newsletters#268]
Stems from #260.

Currently, the Support layout wraps all of its text content in a top-level Group block. Because ad insertion is based on top-level block positions, this causes ads to get rendered in the wrong place, visually. Let's examine why Support uses that Group block and if we can tweak it to improve ad spacing.

**Comment by adekbadek** [comment]
Can be closed as the ads in groups issue was resolved in #260
