### ISSUE TITLE
sendTestEmail should be provider specific

### ISSUE THREAD

**Issue by janus-reith** [Automattic/newspack-newsletters#270]
Although much of the mailchimp logic has been refactored to allow for multiple providers,
the testing currently is hardcoded to use the mailchimp API Endpoint: https://github.com/Automattic/newspack-newsletters/blob/e7b1f83fb8d119c0fe4aa5e4e9fd2f7db28716b4/src/newsletter-editor/testing/index.js#L34

**Comment by adekbadek** [comment]
Thanks for spotting that! It's been changed in #274
