### ISSUE TITLE
Add Support For Preview Text

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-newsletters#275]
From Mailchimp doc https://mailchimp.com/help/edit-your-emails-subject-preview-text-from-name-or-from-email-address/:

> When you send an email, your recipients see the subject line, preview text, from name, and from email address first. It's important for these details to be recognizable and consistent, so recipients are more likely to open your campaigns. When and how you edit this information depends on the type of email campaign you're working with.

The plugin currently supports From Name, From Email, and Subject Line. We should add support for Preview Text. This would probably take the form of a `TextArea` control in the Provider sidebar. There is API support for this field in the `settings` object of a Campaign (https://mailchimp.com/developer/reference/campaigns/).

**Comment by adekbadek** [comment]
There's the [`mj-preview` MJML component](https://mjml.io/documentation/#mj-preview) – that'd be ESP agnostic.
