### ISSUE TITLE
Sponsors: exclude sponsored/underwritten posts from Posts Inserter?

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-newsletters#294]
Now that we're working on [sponsored content](https://github.com/Automattic/newspack-sponsors), we'll want to think about how to handle sponsored and underwritten posts in Newsletters. I can think of two options:

1. Exclude sponsored content from being selectable or appearing in Posts Inserter
2. Add styles for sponsors in case a publisher might want to highlight a sponsored or underwritten post

**Comment by allykmyta** [comment]
TFE has asked for feature # 2 as well as being able to show the sponsor's name rather than the author's.

**Comment by gamebits** [comment]
Noozhawk has also asked for this feature, including that the sponsor's byline be prefixed with "Sponsored by" instead of just "By".

**Comment by dkoo** [comment]
Migrated these to tasks in our internal task board.

**Comment by gamebits** [comment]
`1200550061930446-as-1203366842368233`
