### ISSUE TITLE
Posts Inserter – handle post subtitle

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-newsletters#295]
The Newspack Theme [adds the article subtitle feature](https://github.com/Automattic/newspack-theme/blob/99c14355349550d348e15fe276279151e3c8c027/newspack-theme/js/src/post-subtitle/index.js#L34). If an article has a subtitle, the Posts Inserter should display it, with the ability to toggle its visibility. This should work analogically to  how post excerpt is handled:

![image](https://user-images.githubusercontent.com/7383192/90278783-47c0bc80-de68-11ea-8ec8-51f54446824b.png)

**Comment by miguelpeixe** [comment]
Implemented by #348

**Comment by miguelpeixe** [comment]
Subtitle and excerpt are different things, reopened issue.
