### ISSUE TITLE
Public newsletters – bulk, quick change option

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-newsletters#325]
A feature request – enable user to bulk change the public status of newsletter posts.

**Comment by claudiulodro** [comment]
To expand on this issue:

**Currently when editing a Newsletter there is this toggle:**

<img width="267" alt="Screen Shot 2021-06-10 at 11 03 51 AM" src="https://user-images.githubusercontent.com/7317227/121574971-a8168100-c9db-11eb-97ab-76196460869d.png">

**When that toggle is toggled on, a published Newsletter can be visited and read like a regular post:**

<img width="453" alt="Screen Shot 2021-06-10 at 12 20 02 PM" src="https://user-images.githubusercontent.com/7317227/121584690-9a1a2d80-c9e6-11eb-9861-06875ec0c164.png">

**When that toggle is toggled on, a published Newsletter is also visible on the frontend of the site in category archives and on the Newsletter archive:**

<img width="418" alt="Screen Shot 2021-06-10 at 12 19 42 PM" src="https://user-images.githubusercontent.com/7317227/121584612-82db4000-c9e6-11eb-85b8-840514c54ee1.png">

**There are two improvements we'd like to see on the Newsletters admin screen:**

<img width="820" alt="Screen Shot 2021-06-10 at 12 21 34 PM" src="https://user-images.githubusercontent.com/7317227/121584920-d8175180-c9e6-11eb-9ce4-f8fce9eb4e8f.png">

**1. The ability to make newsletters public/non-public using the Bulk Actions dropdown.
2. The ability to make newsletters public/non-public using the Quick Edit feature.**
