### ISSUE TITLE
Add "open this email in a browser" top line to newsletters

### ISSUE THREAD

**Issue by iamstevebeatty** [Automattic/newspack-newsletters#334]
We thought this was something Mailchimp added, much as it adds the footer. But nope. Here are three examples from my inbox. I kinda like the one you can style to match your colors. 

![Screen Shot 2020-09-11 at 1 17 44 PM](https://user-images.githubusercontent.com/48489469/92959325-35b74700-f431-11ea-807d-bbb2ce9f7160.png)
![Screen Shot 2020-09-11 at 1 15 27 PM](https://user-images.githubusercontent.com/48489469/92959217-07396c00-f431-11ea-80cf-e271f8449635.png)
![Screen Shot 2020-09-11 at 1 15 38 PM](https://user-images.githubusercontent.com/48489469/92959218-07d20280-f431-11ea-9d35-2a3ec06e38b4.png)

**Comment by adekbadek** [comment]
Superseded by broader issue with merge tags support - https://github.com/Automattic/newspack-newsletters/issues/452
