### ISSUE TITLE
Reusable block with image doesn't work on newsletter send

### ISSUE THREAD

**Issue by jckeen** [Automattic/newspack-newsletters#344]
I created a reusable block with a black background and an image for our newsletters. It is the first block within the newsletter. In preview, it shows, but when sending a test email it strips away the reusable block. I tested it again by creating a block once more, with just an image and no background color, then added as a reusable block. On test - no image came through. 

Finally, I converted it to a regular block, sent the test email, and it worked just fine.

**Comment by philipjohn** [comment]
Marking this as a bug as another publisher had this unexpected experience and I just confirmed it myself.

Steps to reproduce:

1. Create a newsletter and send yourself a test
2. Observe that the email contains everything as expected
3. Convert any block, or collection of blocks, to a re-usable block
4. Send yourself another test and observe that the re-usable block is now missing
