### ISSUE TITLE
Re-publishing a draft sent newsletter 

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-newsletters#361]
_Extracted from https://github.com/Automattic/newspack-newsletters/issues/357_

1. Change a **sent** email to draft somehow (easiest way is using the Quick Edit):

<img width="406" alt="Screen Shot 2020-10-16 at 4 48 59 PM" src="https://user-images.githubusercontent.com/7317227/96323154-cf45bb80-0fd0-11eb-8d76-eb0e5da05222.png">

2. Edit the email. Observe there is no way to publish it.

<img width="1333" alt="Screen Shot 2020-10-16 at 4 49 53 PM" src="https://user-images.githubusercontent.com/7317227/96323177-d79df680-0fd0-11eb-96f8-76933b4a5330.png">

**Recommended solution**: Not sure. I think we either need to prevent this state from being reached or add a way to change the status on the Edit Newsletter screen.

**Comment by dkoo** [comment]
I think we should prevent this state because it shouldn't be possible to "unsend" and re-send a newsletter that was already sent. Perhaps we can hide the status controls in the Quick Edit menu?

**Comment by adekbadek** [comment]
The select [is hard-coded](https://core.trac.wordpress.org/browser/trunk/src/wp-admin/includes/class-wp-posts-list-table.php), so the only solution is hiding it with CSS.

**Comment by adekbadek** [comment]
Closed by https://github.com/Automattic/newspack-newsletters/pull/798, which disallows reverting status to draft.
