### ISSUE TITLE
MailChimp: Customize automatic footer on all newsletters

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-newsletters#366]
Right now, when you use MailChimp as a newsletter provider, it appends a footer automatically, with its suggested items (like address, and unsubscribe links).

Normally when you build newsletters in MailChimp, you can customize this area, but when using the Newspack Newsletters, it always appears to fall back to the default:

![image](https://user-images.githubusercontent.com/177561/97629267-16797680-19eb-11eb-9740-37d1f970a31c.png)

It would be ideal if there was a way to change the default footer in MailChimp (as long as it meets their guidelines), and have it be used by any newsletters created by this plugin.

**Comment by jeffersonrabb** [comment]
Mailchimp inserts the default footer if a certain set of required merge fields are not found in the newsletter body. Here's an example of custom footer markup that Mailchimp would allow through without adding the default footer:

```
This email was sent to <a href="mailto:*|EMAIL|*">*|EMAIL|*</a>.
<a href="http://*|ABOUT_LIST|*">Why did I get this email?</a>
<a href="http://*|UNSUB|*">Unsubscribe from this list</a>
<a href="*|UPDATE_PROFILE|*">Update subscription preferences</a></p>
<p>*|LIST:ADDRESSLINE|*</p>
```

This means the newsletter author could build all of these requirements directly into the newsletter content. However there are a couple of issues in the plugin that will break these merge fields. 

1) The `href`s will get a `utm_source` param appended. This seems to cause problems and shouldn't be done when the `href` value is a merge tag.
2) I believe this is a Gutenberg feature but when setting a link that isn't a valid URL, `http://` is prepended. 

Once these two issues are resolved an editor will be able to create custom footers directly in the editor.
