### ISSUE TITLE
Linked headlines don't retain color specified in Heading block

### ISSUE THREAD

**Issue by iamstevebeatty** [Automattic/newspack-newsletters#409]
The plugin gives the ability to change headline colors, but it doesn't stick for any that are links -- and that's all the ones that a Post Inserter brings in, unfortunately. 

What I want:
![Screen Shot 2021-03-01 at 2 08 08 PM](https://user-images.githubusercontent.com/48489469/109553089-3358b000-7a98-11eb-942a-42f187ad75a4.png)

What I get:
![Screen Shot 2021-03-01 at 2 07 55 PM](https://user-images.githubusercontent.com/48489469/109553113-3ce21800-7a98-11eb-9f77-68c7340bae3c.png)

**Comment by jeffersonrabb** [comment]
The issue is reproducible in the Gmail web client. In MacMail the headline color works properly.

**Comment by jeffersonrabb** [comment]
Headlines with link colors produced in the Mailchimp editor do render properly in the Gmail web client. The difference is that Newspack Newsletters applies the color to the `h3` element, while Mailchimp wraps the text in a `span` with the color applied.

### Newspack Newsletters markup:
<img width="490" alt="Screen Shot 2021-03-02 at 5 29 13 AM" src="https://user-images.githubusercontent.com/1477002/109635673-a6097000-7b18-11eb-87c9-8bf87911f1a2.png">

### Mailchimp markup:
<img width="585" alt="Screen Shot 2021-03-02 at 5 28 40 AM" src="https://user-images.githubusercontent.com/1477002/109635700-adc91480-7b18-11eb-9756-b1ef3152df61.png">
