### ISSUE TITLE
Allow custom styles in email-template.mjml.php

### ISSUE THREAD

**Issue by ericjlubbers** [Automattic/newspack-newsletters#417]
Hi all!

I've been using MJML templates for our newsroom's emails for a year or so and have a series of templates that are rock-solid and are a big part of our newsroom branding. We just got access to this plugin via Lede, but right now there is no way to import our styles into the mjml template. We're currently not using the plugin at all for this reason and I would really like to bring it into our workflow.

An ideal execution could be as simple as as an optional field (with plenty of warnings about it being an advanced feature) under the styling menu that would allow a user to overwrite everything in the `<mj-style>` tag in email-template.mjml.php.

That feature would basically instantly take this plugin from unusable to invaluable in our newsroom.

**Comment by adekbadek** [comment]
Hi!

Is this just about adding CSS?

**Comment by ericjlubbers** [comment]
Shoot, sorry @adekbadek, I didn't have my notifications configured properly and missed your note.

Yes, basically, this is about adding a custom stylesheet as an alternative to the default.

The reason I would advocate for the option to drop in a complete override vs. building in a menu to allow for basic changes like typeface, etc., is that my layouts include styles for elements specific to our newsroom, like pullquotes, section headers, hr's etc. Seems like the shortest development path with the most flexibility for newsrooms that include people with intermediate email design skills.

I would also like the ability to include reusable Custom HTML Gutenberg blocks so we can have repeatable pieces and custom ad blocks, but that's a separate issue I'll file shortly.
