### ISSUE TITLE
Minor enhancement -- take away alternate sort methods from Post Inserter

### ISSUE THREAD

**Issue by iamstevebeatty** [Automattic/newspack-newsletters#427]
I have trouble seeing how anyone would want to order their posts by the oldest first. Or by alpha order. 

I assume we have this option for the Homepage Posts block, too, but decided not to clutter the UI with it.

**Comment by dkoo** [comment]
@jeffersonrabb and @adekbadek, thoughts? I always want to check with the team when it comes to taking away features rather than adding them.

**Comment by adekbadek** [comment]
I don't have a strong opinion here, maybe this feature is not that useful 🤷‍♀️
