### ISSUE TITLE
Template Picker Disappears After Period Of Inactivity

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-newsletters#45]
When a new Newsletter is created the template modal appears. If there is no interaction with the modal, eventually it disappears by itself. This is probably due to an auto-save. @thomasguillot had noted this problem earlier and I thought it was resolved, but it isn't...

**Comment by adekbadek** [comment]
Yes, that's because of autosave. The condition for the modal uses `isEditedPostNew` selector, which after an autosave returns false.
