### ISSUE TITLE
Mailchimp - support merge tags

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-newsletters#452]
Mailchimp supports dynamic markup insertion via [merge tags](https://mailchimp.com/help/all-the-merge-tags-cheat-sheet/) - the plugin should offer a block that allows for merge tags insertion. For starters, these look like the most useful ones:

- Creates a View this email in your browser link to your campaign page - `*|ARCHIVE|*`
- Inserts your subscriber's first name if it's available in your audience - `*|FNAME|*`
- Inserts your subscriber's last name if it's available in your audience - `*|LNAME|*`
- Populates your campaign with your Twitter avatar, follower, tweet, and following counts; and a follow link - `*|TWITTER:PROFILE|*`

**Comment by tmmbecker** [comment]
The Real News has mentioned this as one of the primary reasons that they're not actively using our Newsletters feature.
