### ISSUE TITLE
Multiple users editing the same newsletter: content gets lost

### ISSUE THREAD

**Issue by dkoo** [Automattic/newspack-newsletters#495]
A publisher reported bugs when multiple WP users edit the same newsletter. Sequence of events:

1. User A (admin user) creates a newsletter and saves a draft.
2. User B (also admin user) edits the draft.
3. User B makes changes to the draft and saves.
4. User B sends a test email. The test email is missing changes and content, and has unexpected styles (wrong text color).
5. User B re-saves the draft and re-sends a test email. This time the test email looks correct.

Is something happening on the plugin side that might be causing this?

**Comment by miguelpeixe** [comment]
I followed these steps and was not able to reproduce the problem. My test email was sent with the most recent changes (text and colors).

I'd guess that some cycle or meta update is also updating `email_html_meta` with the value [provided through localization](https://github.com/Automattic/newspack-newsletters/blob/v1.29.1/includes/class-newspack-newsletters-editor.php#L169), which would explain missing changes.

**Comment by iamstevebeatty** [comment]
@miguelpeixe MLK50 had this problem again today. See what she did to solve it here. https://newspack-pub.slack.com/archives/C011YNC4B24/p1627678388019600

**Comment by miguelpeixe** [comment]
Thank you for reporting @iamstevebeatty!

With further testing, I was still not able to reproduce the problem locally. While investigating I verified that we can improve how we perform content synchronization with Mailchimp and how we handle potential errors. #534 implements these changes and hopefully resolve or, at least, bring more light to the root cause of this bug.

**Comment by miguelpeixe** [comment]
We've identified that the issue persisted due to outdated revisions being saved and replacing the latest content.

If it's identified that the issue is still persisting without older revisions replacing newer content we'll reopen.
