### ISSUE TITLE
CI task for wporg release is not working

### ISSUE THREAD

**Issue by miguelpeixe** [Automattic/newspack-newsletters#571]
The attempt from #568 did not solve the problem introduced by the php-scoper dependency on #548.

The CI task commits to svn, which has a configured pre-commit hook that lints PHP files from `tags` directory. The directory contains vendor files that should not be processed by the linter:

https://app.circleci.com/pipelines/github/Automattic/newspack-newsletters/1372/workflows/c77e739b-44d2-4d5f-aff9-04c85a222b36/jobs/3127

The linter, that shouldn't process these files, ends up processing an invalid PHP file used by php-scoper for testing.

**Comment by kariae** [comment]
Going back a bit on this, I see that we implemented `php-scoper` to [fix the Guzzle namespace conflict](https://github.com/Automattic/newspack-newsletters/pull/548). 

Can't we just implement [another HTTP client](https://github.com/symfony/http-client)? I see that we use it only in the [Constant Contact SDK class](https://github.com/Automattic/newspack-newsletters/search?q=GuzzleHttp) so the change will be easy, or we do need to stay with Guzzle for a specific reason?

**Comment by miguelpeixe** [comment]
It's a good idea. Although it is for Guzzle, it actually is a concern for any popular dependency. If we use another HTTP client that gets an old version imported by a different plugin we might face the same issues.

If we know that this new HTTP client doesn't have too many breaking changes in the past major releases, I believe it will be safer to assume we don't need to isolate it through a custom namespace.

**Comment by kariae** [comment]
Hum, I got your point.

[The changelog](https://github.com/symfony/http-client/blob/5.3/CHANGELOG.md) seems clean from breaking changes. But as you said this might happen for any popular dependency. A hacky trick would maybe then be to keep using `php-scoper` and excluding its tests files from the release since I guess the file breaking the linter is from the tests folder and is not necessary for production.

**Comment by miguelpeixe** [comment]
Improving how we implement `php-scoper` is how I would recommend we handle this issue (#574). Your comment made me wonder if using plain [curl](https://www.php.net/manual/en/book.curl.php) is a viable alternative, though. Since the SDK we built is very simple, I don't think it would be too complex.

If we decide to maintain the `php-scoper`, the reference I used for our implementation is from [Yoast SEO](https://github.com/Yoast/wordpress-seo). It can certainly be improved from how I initially built it.

**Comment by kariae** [comment]
> Improving how we implement php-scoper is how I would recommend we handle this issue (#574)
+1 for this. If you think you can improve how `php-scoper` is implemented today, let's go for this option, it's the proper one.

**Comment by adekbadek** [comment]
> if using plain `curl` is a viable alternative

Or `wp_safe_remote_*` functions (e.g. [`wp_safe_remote_get`](https://developer.wordpress.org/reference/functions/wp_safe_remote_get/))

**Comment by miguelpeixe** [comment]
> Or `wp_safe_remote_*` functions (e.g. [`wp_safe_remote_get`](https://developer.wordpress.org/reference/functions/wp_safe_remote_get/))

I really like that. +1
