### ISSUE TITLE
Make author page inaccessible

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-newsletters#626]
Enabling this plugin is resulting in author URL inaccessible i.e. 404 error, page not found.

**Comment by miguelpeixe** [comment]
I was not able to reproduce the issue. Is this happening to all your author archives?

Can you test with [v1.35.1](https://github.com/Automattic/newspack-newsletters/releases/tag/v1.35.1) to see if the problem persists on this version?

**Comment by yogeshbeniwal** [comment]
@miguelpeixe Works well with v1.35.1, issue starting from v1.36.0. Tested to be not working on multiple website.

**Comment by miguelpeixe** [comment]
I didn't notice that the v1.36.1 wasn't released on wp.org. #622 has the fix and should be available soon!
