### ISSUE TITLE
Invalidated Button Block In Templates

### ISSUE THREAD

**Issue by jeffersonrabb** [Automattic/newspack-newsletters#63]
In three of the templates there is a `Button` block that is being marked as invalid by Gutenberg (v7.8.1). 

#### Templates
- Breaking News
- Breaking News (no image)
- Support

#### Invalidation Error

```
Content generated by `save` function:

<div class="wp-block-button alignnone wp-block-button__link"><a class="wp-block-button__link" href="#">Read more</a></div>

Content retrieved from post body:

<a class="wp-block-button wp-block-button__link" href="#">Read more</a>
```

<img width="1597" alt="Screen Shot 2020-04-17 at 10 15 19 AM" src="https://user-images.githubusercontent.com/1477002/79578657-813d1300-8094-11ea-8224-3f2d8bd56332.png">

**Comment by jeffersonrabb** [comment]
After updating to latest Gutenberg (7.9.1) the issue is resolved.

**Comment by adekbadek** [comment]
I think that might just be the start of backwards compatibility issues – storing the Gutenberg-generated HTML as templates is prone to those 😬 

I propose to store templates as ["template arrays"](https://developer.wordpress.org/block-editor/developers/block-api/block-templates/), so instead of 
```
<!-- wp:heading -->\n<h2>The main story headline goes here</h2>\n<!-- /wp:heading -->
```
we'd have
```
[ 'core/heading', { content: 'The main story headline goes here', level: 2 } ]
```
WDYT?

**Comment by jeffersonrabb** [comment]
> I think that might just be the start of backwards compatibility issues – storing the Gutenberg-generated HTML as templates is prone to those

I'm not sure that newsletters are any more or less error-prone than any other type of post. The only thing that makes the content of newsletters different from regular posts is the limited set of available blocks. Unexpected block deprecatation may occur 😬  but I don't think there's any reason to treat the internal structure of this custom post type differently from others.

**Comment by adekbadek** [comment]
Perhaps I did not articulate the proposition clearly – it's not about storing the newsletter posts differently than other posts. It's just about how templates are handled.
What we have now is JSON files with blobs of HTML and some code to replace special tokens in those (`template_token_replacement`). That's not very manageable, is pretty error-prone, and editing these templates is tough.
But there's an [idiomatic way of handling block templates](https://developer.wordpress.org/block-editor/developers/block-api/block-templates/), which allows for much better readability, maintenance, and ensures there would be no backwards compatibility issues like this one. So what I propose is rewriting templates in this format. This would also lay some groundwork for #31 .

**Comment by jeffersonrabb** [comment]
Oh interesting, I misunderstood, apologies. The approach we're taking is based on how Patterns are handled. The workflow for creating a Pattern is: 

1) build the blocks normally in the editor
2) create a reusable block
3) go to the reusable blocks management page 
4) export the JSON. 

We did it this way in `newspack-blocks` to align with Core's approach, and I followed the same approach for Newsletter Templates. @thomasguillot what are your thoughts on this possible change in approach?

**Comment by adekbadek** [comment]
#31 would probably be implemented by storing the user's layouts in `wp_options`. So from our perspective, adding a new default layout would be just pulling an option value and copying it to codebase. 
Anyway, this can be done in a way that would not add any overhead to our development process.

**Comment by thomasguillot** [comment]
I'd be up for @adekbadek's proposition.

JSON files are quite tricky to maintain and as it stands, a pain to have translatable strings!

**Comment by jeffersonrabb** [comment]
Just to play it out, is there any way reusable blocks or something very similar could answer the "user's layouts" question more easily, and more in line with core?

**Comment by adekbadek** [comment]
I'll explore the possibility of using the reusable blocks infrastructure for newsletters layouts 👍

**Comment by jeffersonrabb** [comment]
Closing since the original issue is resolved.
