### ISSUE TITLE
Multiple newsletters

### ISSUE THREAD

**Issue by yogeshbeniwal** [Automattic/newspack-newsletters#636]
Down the road it will be good to have feature to allow users to sign up for multiple newsletters.

-  Current Jetpack mailchimp block in use support attaching to one audience only. Block to provide option for users to select and sign up from list of available newsletters
- Segmentation and analytics as per newsletter

Use Case:

- Daily/Weekly/Monthly
- Topic Wise (Campaign targeting using category in popups exists)

Requirement to be more refined after discussion.

**Comment by adekbadek** [comment]
Example: https://chicagoreader.com/email-newsletters-signup/
