### ISSUE TITLE
Sidebar enhancements

### ISSUE THREAD

**Issue by pablohoneyhoney** [Automattic/newspack-newsletters#64]
Group and name functions more contextually to the user need. Likely worth to break in smaller issues @thomasguillot 

1. Expand panel by default, if possible once user lands on the editor. 
2. Call panel _Newsletter_, without _Settings_, until we find a better naming convention. 
3. Subject field to absorb by default the _title_ or first _block title_  instead of date. 
4. Remove dividers, just divide after Name field.
5. Add label _Testing_ before CTA _Send a Test Email_ and link to Mailchimp. No divider in-between these. 
 
<img width="366" alt="Screen Shot 2020-04-17 at 12 53 00 PM" src="https://user-images.githubusercontent.com/25516611/79597609-945ddc00-80b0-11ea-9072-54841b1981e0.png">

**Comment by jeffersonrabb** [comment]
> Subject field to absorb by default the title or first block title instead of date.

The Subject is actually the Title of the post, and it is set when the post is created. It need not be the date, but it would be difficult and potentially confusing for the user if it changed based on the content of the newsletter.

**Comment by thomasguillot** [comment]
__Current state of the sidebar (20200422)__

![sidebar-current-state](https://user-images.githubusercontent.com/177929/79997793-d5d7f800-84b1-11ea-9134-1a16dd003d4f.png)

**Comment by pablohoneyhoney** [comment]
If you contextualize this sidebar within the editor, we have too many primary CTAs. Sidebar should host secondary or tertiary, ideally.
