### ISSUE TITLE
"Add layout" CTA

### ISSUE THREAD

**Issue by pablohoneyhoney** [Automattic/newspack-newsletters#66]
The _Call to Action_ (CTA) should say _Use this Design_ or _Use this Layout_, without the name of the layout to avoid lengthy buttons. 

<img width="295" alt="Screen Shot 2020-04-17 at 12 35 31 PM" src="https://user-images.githubusercontent.com/25516611/79599407-6b8b1600-80b3-11ea-852e-9b0d4b99ad06.png">

**_Use this Design_** sounds more user friendly.

**Comment by adekbadek** [comment]
Done in #74
