### ISSUE TITLE
Add access to wp-admin when in selecting layout

### ISSUE THREAD

**Issue by pablohoneyhoney** [Automattic/newspack-newsletters#67]
When selecting a design, user should be able to go back to wp-admin. Add the WP logo traetment from the editor. 

<img width="387" alt="Screen Shot 2020-04-17 at 12 23 14 PM" src="https://user-images.githubusercontent.com/25516611/79599571-b7d65600-80b3-11ea-9275-1fb00a10a2f9.png">

**Current back button in the editor**
<img width="102" alt="Screen Shot 2020-04-17 at 2 01 07 PM" src="https://user-images.githubusercontent.com/25516611/79599657-e6543100-80b3-11ea-9533-47b596656bf6.png">

**Comment by thomasguillot** [comment]
Fixed in https://github.com/Automattic/newspack-newsletters/pull/74
