### ISSUE TITLE
Add Settings link to wp-admin

### ISSUE THREAD

**Issue by pablohoneyhoney** [Automattic/newspack-newsletters#68]
User should associate a Settings capability within Newspetter in the left sidebar. 
Adding a **_Settings_** access will help solve that.

<img width="377" alt="Screen Shot 2020-04-17 at 12 21 05 PM" src="https://user-images.githubusercontent.com/25516611/79600096-9f1a7000-80b4-11ea-8bf7-f639ea6efaf6.png">

**Comment by thomasguillot** [comment]
Agreed. Let's move the settings to the same sub-menu. cc @jeffersonrabb 

![newspack-newsletters-settings](https://user-images.githubusercontent.com/177929/79632416-e0635c00-8156-11ea-970b-6eb28b83c25b.png)

_Note: we should also add some help text for users to easily retrieve their API keys_

**Comment by jeffersonrabb** [comment]
Once this change is made, should we remove the link from Settings that is there currently? 

<img width="1335" alt="Screen Shot 2020-04-19 at 10 56 17 AM" src="https://user-images.githubusercontent.com/1477002/79691282-83d27080-822c-11ea-830b-70a64bdeaaf5.png">

**Comment by thomasguillot** [comment]
> Once this change is made, should we remove the link from Settings that is there currently?

@jeffersonrabb I'd say so. There's no point have the settings in 2 different places. It will just confuse users.
