### ISSUE TITLE
Layout label styles

### ISSUE THREAD

**Issue by pablohoneyhoney** [Automattic/newspack-newsletters#69]
In my case, the previews are reading some theme variables, and is displaying the labels too tightly attached to the preview image. 

<img width="173" alt="Screen Shot 2020-04-17 at 12 28 47 PM" src="https://user-images.githubusercontent.com/25516611/79600323-f9b3cc00-80b4-11ea-9a84-6d4e23b8483f.png">

<img width="2243" alt="Screen Shot 2020-04-17 at 12 34 33 PM" src="https://user-images.githubusercontent.com/25516611/79600410-1f40d580-80b5-11ea-8372-36cf6867d76e.png">

**Comment by jeffersonrabb** [comment]
There is a PR that removes all theme editor styling: https://github.com/Automattic/newspack-newsletters/pull/8. Once this has been merged none of this styling will be present. I'll add this issue to that PR so it closes automatically at merge.
