### ISSUE TITLE
Inconsistent iframe styles

### ISSUE THREAD

**Issue by miguelpeixe** [Automattic/newspack-newsletters#695]
The fix for nested iframes styles introduced by #685 is behaving inconsistently

![image](https://user-images.githubusercontent.com/820752/149991759-efe453a9-9a27-4c16-b399-283b3d76a1ec.png)

**Comment by thomasguillot** [comment]
I think I fixed this with my PR: https://github.com/Automattic/newspack-newsletters/pull/712.

@miguelpeixe would you mind confirming?
