### ISSUE TITLE
Preview images in layouts

### ISSUE THREAD

**Issue by pablohoneyhoney** [Automattic/newspack-newsletters#71]
I believe there's the intent to pull images from the actual site. 

If not, we should add a default generic image that looks good instead of a preview of the placeholder. 

<img width="373" alt="Screen Shot 2020-04-17 at 12 31 10 PM" src="https://user-images.githubusercontent.com/25516611/79601169-62e80f00-80b6-11ea-8c6f-e31db1b0f9e0.png">

**Comment by adekbadek** [comment]
The layout with an image placeholder has been removed some time ago.
