### ISSUE TITLE
Layout selection within sidebar

### ISSUE THREAD

**Issue by pablohoneyhoney** [Automattic/newspack-newsletters#72]
Add the ability to change the layout within the editor's sidebar if needed, without going back. Similarly to how we can change a style of a block.

<img width="277" alt="Screen Shot 2020-04-17 at 2 25 59 PM" src="https://user-images.githubusercontent.com/25516611/79601810-6a5be800-80b7-11ea-9a2e-25a7fc227797.png">

**Comment by thomasguillot** [comment]
We could do this in 3 steps:

### 1. In the sidebar

![1 sidebar](https://user-images.githubusercontent.com/177929/79761455-65966e80-8319-11ea-83a6-72534c6af243.png)

Preview + "Change Layout" button

### 2. Modal to warn the user

![2 modal](https://user-images.githubusercontent.com/177929/79761505-76df7b00-8319-11ea-981a-d96d60c37178.png)

When the user click in the sidebar on "Change Layout", a modal comes up to warn the user that they might lose all customisation if they decide to change the layout.

### 3. Select a layout modal

When the user confirm they want to change the layout they will see the initial modal where we offer all the different layouts.

cc @jeffersonrabb

**Comment by jeffersonrabb** [comment]
Wouldn't the Sidebar rendering of the current layout be identical to what's in the editor?

**Comment by thomasguillot** [comment]
I think it should match the selected Layout and not the editor since it's what the user selected.
