### ISSUE TITLE
Add banner once plugin is activated

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/newspack-newsletters#73]
When the user activate the plugin we should display a dismissible banner to allow them to continue the setup by providing their API keys.

![newspack-newsletter-activation-banner](https://user-images.githubusercontent.com/177929/79632479-67183900-8157-11ea-9c36-6c6d39c5d790.png)

**Comment by jeffersonrabb** [comment]
Is this needed even once https://github.com/Automattic/newspack-newsletters/issues/52 is addressed?

**Comment by thomasguillot** [comment]
> Is this needed even once #52 is addressed?

Yes since it can be dismissed.
