### ISSUE TITLE
ActiveCampaign provider integration

### ISSUE THREAD

**Issue by claudiulodro** [Automattic/newspack-newsletters#765]
As we work closer with BlueLena, it would be good to get a proper integration with ActiveCampaign instead of forcing those users to use the Manual provider. In their work so far, BlueLena has found that the Manual provider adds extra friction to the workflow which a proper ActiveCampaign integration would reduce.

[Here's the documentation for the ActiveCampaign API.](https://developers.activecampaign.com/reference/overview)

**Comment by tmmbecker** [comment]
I looked at a few who have moved to BlueLena. None of them use our newsletters despite having worked with BlueLena to get it set up. Springfield wants to use our solution despite the friction but is finding the manual option to be pretty clunky.
