### ISSUE TITLE
Add support for Co-Authors Plus

### ISSUE THREAD

**Issue by dnalla1928** [Automattic/newspack-newsletters#805]
In the normal setup of Newsletters, you can reassign the author.  However, when you activate Co-Author Plus plugin, the native author box is removed and there is no other way to reassign the author inside the Newsletters panel.  You can still reassign from the dashboard and using the Quick Edit function.

**Comment by tmmbecker** [comment]
Can we add the CAP authors selector to the Newsletter panel? Without it, those who choose to make the newsletter public can only use the Quick Edit option to change the author. 

Without CAP, I can use the native author selector:

<img width="318" alt="Screen Shot 2022-04-30 at 10 46 59" src="https://user-images.githubusercontent.com/22805865/166110318-3cb64003-d4b5-4db8-9dc2-9b110c52c602.png">

With CAP there is nowhere to select an author for the web-facing version:

<img width="311" alt="Screen Shot on 2022-04-30 at 10-47-35" src="https://user-images.githubusercontent.com/22805865/166110346-8d21ad5b-2f60-4921-b9ba-cbe04558f1f5.png">

In standard posts, CAP includes an Authors section in the panel. 

<img width="329" alt="Screen Shot on 2022-04-30 at 10-49-14" src="https://user-images.githubusercontent.com/22805865/166110444-c2522c73-61fa-4bcc-81ba-c075e24119d2.png">

**Comment by tmmbecker** [comment]
@miguelpeixe could we prioritize this for the next release?
