### ISSUE TITLE
Posts Inserter: include Listings as an option

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/newspack-newsletters#843]
While it doesn't make sense to include any other post type, adding the ability to insert listings will help publishers to highlight their listings in newsletter content where applicable, particularly once we get to self-serve and improve our capacity to support paid listings. 

As requested by SacObserver.

**Comment by angshah** [comment]
+1 here for a being able to pull listings into newsletters.

**Comment by gamebits** [comment]
ENN & ML both want this feature.
